### ISSUE TITLE
Version for older Zabbix?

### ISSUE THREAD

**Issue by Dunuin** [blind-oracle/zabbix-ecc#1]
Hi,

I would like to test your template but I can'T import it because I am using Zabbix 5.0.14 LTS and it was exported with zabbix 5.2 so its not usable with version below 5.2. I tired to edit the template to "<version>5.0</version>" but then other errors occure while importing like "Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/item_prototypes/item_prototype(1)/preprocessing/step(1)": unexpected tag "parameters".".

Do you have any older version that will work with older zabbix versions?

**Comment by blind-oracle** [comment]
Sorry, but I don't have it. But I took a look and see that you just need to rename `parameters` to `params`. If that works for you you can do a PR here to add a template for 5.0 for other people to use.

**Comment by Dunuin** [comment]
After changinh everything to params i get this:
`Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/item_prototypes/item_prototype(1)/preprocessing/step(1)/params": a character string is expected.`
